name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Установка зависимостей проекта
          pip install -r requirements.txt
          # Установка фиксированных версий линтеров и тестового фреймворка
          pip install black==25.9.0 isort==6.0.1 flake8==7.3.0 mypy==1.18.2 pytest==8.4.2

      - name: Run black
        run: black --check . || true  # || true позволяет увидеть ошибки без остановки workflow

      - name: Run isort
        run: isort --check-only . || true

      - name: Run flake8
        run: flake8 . || true

      - name: Run mypy
        run: mypy . || true

      - name: Run tests
        run: pytest -v tests
